name: Build and Deploy Myformatic
on:
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.1.3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables and Cache Docker layers
        run: |
          echo "NEXT_PUBLIC_GOOGLE_DEVELOPER_KEY=$(echo AIzaSyCGLwjJkFBscBonfevnjcYnU1VeXAF2e6o)" >> $GITHUB_ENV
          echo "GOOGLE_APP_ID=$(echo ${{ github.ref == 'refs/heads/main' && '946939138329-rr50rin38rpeaam8q4ai2in3pq5e45q1.apps.googleusercontent.com' || '946939138329-p17gced0hvdkd59hc9s1115o3v24pve2.apps.googleusercontent.com' }})" >> $GITHUB_ENV
          echo "BASE_URL=$(echo https://api.myformatic.com)" >> $GITHUB_ENV
          echo "STRIPE_PUBLISHABLE_KEY=$(echo ${{ github.ref == 'refs/heads/main' && 'pk_live_51JZ8LJHam8CyuMKlnuOdzQnbrNnxTWk99SUPr14OxpCmCvBqNpk56JuoufofhBOpmmuUOafPgaWFgzzBEgyB4Jp000ZQSSxxQL' || '' }})" >> $GITHUB_ENV

          # Cache Docker layers
          mkdir -p /tmp/.buildx-cache
          docker pull ghcr.io/abdullah117765/OptimizatingPipeline:latest || true
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker save $(docker history -q ghcr.io/abdullah117765/OptimizatingPipeline:latest | grep -v '<missing>') | gzip > /tmp/.buildx-cache/layers.tar.gz
          echo "::set-output name=cache-key::${{ runner.os }}-buildx-${{ github.ref_name }}-${{ github.sha }}"

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/abdullah117765/OptimizatingPipeline
          tags: |
            type=raw,value=${{ github.ref_name }}

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            APP_NAME=Formatic
            REACT_APP_BASE_URL="http://localhost:3000"
            STRIPE_PUBLISHABLE_KEY="${{ secrets.STRIPE_PUBLISHABLE_KEY }}"
            GOOGLE_APP_ID="${{ secrets.GOOGLE_APP_ID }}"
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          cache-key: ${{ steps.cache.outputs.cache-key }}
